on:
  workflow_dispatch:
    inputs:
      team_group:
        description: 'team_group'
        required: true
        default: 'foo'
        type: string

jobs:
  my_job:
    name: "My job [my_value: ${{ github.event.inputs.my_value }}]"
    runs-on: ubuntu-latest

    steps: