on:
  workflow_dispatch:
    inputs:
      team_group:
        description: 'team_group'
        required: true
        default: 'foo'
        type: string

jobs:

  run-python-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
        env:
          access_token: ${{ secrets.LEANDRO_PROD }}
      - name: Execute Test Script
        run: |
          ls -ltra
          echo ${{ github.repository }}
          echo ${{ github.event_name }}
          echo ${{ github.job }}
          echo ${{ github.ref_type }}
          echo ${{ github.repository_owner }}
          echo ${{ github.run_id }}
          echo ${{ github.sha }}
          echo ${{ github.WORKFLOW }}

          echo "Store: ${{ github.event.inputs.team_group }}"
          pip install -r requirements.txt
          python3 ${{ github.action_path }}\chamada_api.py ${{ secrets.LEANDRO_PROD }} ${{ github.event.inputs.team_group }}
          cat repo_processado.txt