name: Scheduled Job

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '35 09 * * *'

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "This job runs every day at 00:00 UTC"
          # You can add more commands here
