name: Test Python Input
on:
  workflow_dispatch:
    inputs:
      myInput:
        description: 'User Input Here'
        required: true

jobs:
  run-python-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: Execute Test Script
        run: |
          ls -ltra
          echo ${{ github.repository }}
          echo ${{ github.GITHUB_EVENT_NAME }}
          echo ${{ github.GITHUB_JOB }}
          echo ${{ github.GITHUB_REF_TYPE }}
          echo ${{ github.GITHUB_REPOSITORY_OWNER }}
          echo ${{ github.GITHUB_RUN_ID }}
          echo ${{ github.GITHUB_SHA }}
          echo ${{ github.GITHUB_WORKFLOW }}
          
          echo "Store: ${{ github.event.inputs.myInput }}"
          INPUT_STORE=${{ github.event.inputs.myInput }} python3 ${{ github.action_path }}\test.py
