name: 'teste_response'
on:
  workflow_dispatch:
    inputs:
      myInput:
        description: 'User Input Here'
        required: true


jobs:
  capture-pr-number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Ensure jq is installed
      - name: Install jq
        run: sudo apt-get install jq

      - name: Get Pull Request Number
        id: get-pr-number
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          CURL *hnd = curl_easy_init();
          curl_easy_setopt(hnd, CURLOPT_CUSTOMREQUEST, "GET");
          curl_easy_setopt(hnd, CURLOPT_URL, "https://api.github.com/repos/LeandroNunesNascimento/github-actions-test");
          struct curl_slist *headers = NULL;
          headers = curl_slist_append(headers, "Content-Type: application/json");
          headers = curl_slist_append(headers, "Authorization: Bearer $GITHUB_TOKEN");
          curl_easy_setopt(hnd, CURLOPT_HTTPHEADER, headers);
          CURLcode ret = curl_easy_perform(hnd);
         

      - name: Use Pull Request Number
        run: |
          echo "The Pull Request Number is ${{ steps.get-pr-number.outputs.number }}"
