name: 'teste_response'
on:
  workflow_dispatch:
    inputs:
      myInput:
        description: 'User Input Here'
        required: true


jobs:
  capture-pr-number:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Ensure jq is installed
      - name: Install jq
        run: sudo apt-get install jq

      - name: Get Pull Request Number
        id: get-pr-number
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          saida=$(curl --request GET \
          --url "https://api.github.com/repos/LeandroNunesNascimento/teste_info_template" | jq '.'\
          -H "Content-Type: application/json" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $GITHUB_TOKEN")
          
          echo $saida
         

      - name: Use Pull Request Number
        run: |
          echo "The Pull Request Number is ${{ steps.get-pr-number.outputs.number }}"
